Fix/processcreate
Nidev-lab/rolling-process pull request #25
Opened 2024-01-16 22:20 UTC by francop7

2024-01-17 11:32 UTC, Nidev-lab requested changes

2024-01-17 11:32 UTC, Nidev-lab commented on src/components/NewProcess/NewProcess.jsx
> +                  </div> : <></>);
?

2024-01-17 11:32 UTC, Nidev-lab commented on src/components/NewProcess/NewProcess.jsx
> +                  </div> : <></>);
?

2024-01-17 11:32 UTC, Nidev-lab commented on src/components/ProcessDetails/ProcessDetails.jsx
> +      return <MessageProcess value={value} />;
Porque usan el mismo componente? Entiendo que description no deberia mostrarse.

2024-01-17 11:32 UTC, Nidev-lab commented on src/components/ProcessDetails/ProcessDetails.jsx
> +  positionProcess = positionProcess.concat(links);
Esto se puede hacer con un .map y un state

2024-01-18 23:58 UTC, andrescuello7 approved these changes

2024-01-19 00:38 UTC, Nidev-lab approved these changes

2024-01-19 00:39 UTC, merged